# A klinikai gyógyszervizsgálatok célja és módszerei
\chaptermark{Célok és módszerek}

Arra a kérdésre, hogy egy gyógyszer „jó”-e, lehetetlen egyszerűen válaszolni, hiszen ez egy többdimenziós kérdés: számít, hogy biztonságos-e, számít, hogy hatásos-e, számít, hogy megfelelő, állandó minőségben gyártható-e, manapság egyre több esetben számít az ára is. Ezek a kérdések ráadásul sok esetben nem függetlenek sem egymástól, sem a kezelni kívánt betegség jellegétől: egy sok mellékhatást okozó gyógyszer is lehet jó, ha egy gyógyszer nélkül nagyon rossz kilátású betegségben sokat segít, egy kevés mellékhatást okozó gyógyszer is lehet rossz, ha egy gyógyszer nélkül sem túl súlyos betegségen csak kicsit javít. A gyógyszer adására vonatkozó döntés mindig **kockázat-haszon mérlegelés** eredménye; fontos feladat azonban, hogy ehhez a mérlegeléshez a valóságnak megfelelő kiindulási információink legyenek.

Ez az összefoglaló ebből a feladatból most két, az orvoslásban és a közbeszédben is talán legfontosabb kérdésre fog fókuszálni: a hatásosság és a biztonság megítélésére.

## Gyógyszerek empirikus vizsgálata

Egy gyógyszer(jelölt)nek mind a hatásossága, mind a biztonságossága megvizsgálható számos módon. Használhatunk -- és használnak is -- állatkísérleteket, matematikai modelleket, biológiai megfontolásokat és így tovább, ám a folyamat végén, ha a gyógyszer még mindig megfelelőnek tűnik, manapság szinte kivétel nélkül meg kell vizsgálni a gyógyszer hatását -- mind fő-, mind mellékhatásait -- **empirikusan** is, azaz embereknek ténylegesen beadva a gyógyszert, és való életbeli adatokat gyűjtve az ezután történtekről. Ennek során megpróbáljuk a „hat-e a gyógyszer” (ha igen, pontosan mire, mennyire, esetleg milyen gyógyszerrel vagy egyéb kezeléssel együtt alkalmazva) és az „okoz-e mellékhatást a gyógyszer” (ha igen, milyet, milyen súlyosat, mennyire gyakran) kérdéseket megválaszolni. Vegyük észre, hogy a két kérdés nagyon hasonló: mindkét esetben arra vagyunk kíváncsiak, hogy valamilyen esemény előfordulásának a valószínűségét megnöveli-e a gyógyszeres kezelés (csak épp az egyik esetben ez egy pozitív, a másikban egy negatív jellegű esemény). Azt gondolhatnánk, hogy a kérdés nem nehéz, hiszen az előfordulási valószínűséget tudjuk közelíteni azzal, hogy milyen gyakran fordul elő az esemény, így egyszerűen annyit kell tenni, hogy gyűjtünk betegekből egy nagyobb vizsgálati csoportot aki kap gyógyszert és egy másikat, aki nem, majd összehasonlítjuk az adott esemény -- akár pozitív, akár negatív -- gyakoriságát. A valóságban sajnos ennél bonyolultabb a helyzet.

## A confounding problémája

Egy gondolatkísérlettel könnyen illusztrálhatjuk, hogy elvileg^[Az itt bemutatott felfogás, az ún. counterfactual megközelítés valójában csak az egyik lehetséges megközelítése az okozatiság fogalmának. Ez a kérdés azonban részben már a filozófia tárgyköréhez tartozik; a gyakorlati gyógyszervizsgálati munkához, illetve a gyógyszervizsgálati eredmények megértéséhez elégséges az itt bemutatott gondolkodási keret [@greenland1986; @maldonado2002; @maldonado2013; @maldonado2016; @dawid2000].] mi az *ideális* vizsgálati módszer: fogunk egy alanyt, beadjuk neki a gyógyszert, felírjuk mi történik, utána beülünk egy időgépbe, visszamegyünk, *nem* adjuk be a gyógyszert, majd így is felírjuk mi történik. A kettő *különbsége* lesz a gyógyszer *hatása* az adott embernél (akár negatív, akár pozitív hatásról van szó). Az időgép fontos volt, hiszen emiatt mondhatjuk, hogy *minden* körülmény *pontosan* ugyanaz volt, *kizárólag* a kezelés tényében volt eltérés -- ez viszont garantálja, hogy ha a kimenetben találunk eltérést, akkor az *biztosan* a kezelés miatt kellett legyen. Tényleg megtaláltuk tehát a kezelés valódi, okozati hatását.

Időgép híján viszont gondban leszünk a viszonyítással. Ha az alanynak adunk gyógyszert, akkor megtudjuk az egyik érdekes kimenetet, hogy mi történik vele kezelés mellett, de mi a helyzet a másikkal? Honnan tudjuk, hogy mi történt *volna* vele kezelés nélkül? (Hiszen ezt a kettőt kell összevetni.) Sajnos -- ha nincs időgépünk -- sehonnan! Abban a pillanatban, hogy beadjuk a gyógyszert, megsemmisül az a kimenet, hogy mi történt volna gyógyszer nélkül. Ha nem adunk neki gyógyszert, akkor meg pont fordított a helyzet, tudjuk mi történik gyógyszer nélkül, de nem tudjuk -- és nem tudhatjuk -- mi történt volna gyógyszerrel.

Az egyik megoldás, hogy két beteget nézünk: az egyik kap gyógyszert (kezelt beteg), a másik nem (kontroll beteg), és az ő eredményeiket hasonlítjuk *egymáshoz*. Vegyük azonban rögtön észre, hogy ez a megközelítés csak és kizárólag akkor működik, ha igaz az a háttérfeltételezés, hogy a kontroll beteggel történtek mutatják, hogy mi történt *volna* a kezelt beteggel, ha nem kapott *volna* gyógyszert. Ez azonban nem nyilvánvaló, hiszen egy másik emberről van szó! Ő pedig *más* jellemzőiben is eltér(het) azon túl, hogy nem kap gyógyszert, amely jellemzők között lehet olyan, ami hat a vizsgált kimenetre. Mi van akkor, ha a kezelt beteg túlél és a kontroll meghal, de a kezelt beteg fiatalabb volt? Lehet, hogy valójában a kezelésnek semmi szerepe nem volt, egyszerűen a kezelt beteg alacsonyabb életkora a valódi oka a túlélésének! Még az is lehet, hogy a kezelés kimondottan ront a túlélési kilátásain, csak annyival fiatalabb volt, hogy az többet számított.

A legtöbb ember ezt hallva azt mondja, hogy jó, de ez a probléma egyszerűen megoldható: ne egy-egy embert nézzünk, hanem nagyobb csoportokat. Ez valóban fontos lesz, de más miatt! A mostani problémánkon azonban nem segít.

Nézhetünk akár 1000 kezelt beteget is, ha ők fiatalabbak -- nem feltétlenül mind, akár csak átlagosan is -- mint az 1000 kontroll betegünk, akkor pontosan ugyanazzal a problémával fogunk szembesülni: innentől kezdve egyszerre *két* eltérés van a csoportok között, a vizsgált (egyik kap gyógyszert, másik nem), és egy vele együttjáró másik (egyik fiatalabb, másik idősebb). Innentől kezdve, ha találunk is különbséget a túlélők arányában, nem tudhatjuk, hogy az mi miatt van: a vizsgált eltérés miatt, a vele együttjáró másik eltérés miatt (vagy a kettő valamilyen keveréke miatt). Ez első ránézésre meglepő, de drámai problémákhoz vezet: akár még az is előfordulhat, hogy a kezelés kimondottan ártalmas, *és* a túlélők aránya a kezelt csoportban nagyobb! (Ha a kezeltek annyival fiatalabbak, hogy a kisebb életkor jótékony hatása nagyobb, mint a kezelés káros hatása). Ezt a problémát hívjuk angol szóval **confoundingnak**. Nem igazán terjedt el rá magyar megfelelő, de angolul nagyon szemléletes: szó szerint „egybemosódást” jelent, és csakugyan, arról van szó, hogy a vizsgált tényezőbeli eltérés (a becsülni kívánt hatás) összemosódott más eltéréssel vagy eltérésekkel.

Az ilyen változókat, amik ezt a galibát okozzák, tehát amelyekre egyszerre igaz, hogy eltérnek a vizsgált csoportok között *és* hatnak a kimenetre (ha bármelyik nem áll fenn, akkor nincsen baj, gondoljuk végig), szokás confoundernek, vagy magyarul zavaró változónak nevezni.

## A randomizáció szerepe, megfigyeléses és kísérletes vizsgálatok
\chaptermark{Megfigyelés és kísérlet}

Mit tudunk ez ellen tenni? Olyan confoundereknél, amelyekről van információnk (ismerjük az értéküket az egyes alanyokra), rendelkezésre állnak statisztikai megoldások, amikkel segíthetünk a helyzeten. Megtehetjük például, hogy külön vizsgáljuk a gyógyszer hatását csak a fiatalokban és csak az idősekben (rétegzett elemzés). Erre vannak kifinomultabb módszerek is, de bármilyen kifinomultan járunk is el, biztosan nem kezeljük jól a helyzetet abban az esetben, ha eszünkbe sem jut valamelyik változóról, hogy az confounder lehet.

Az ember azt gondolhatná, hogy ez ellen a probléma ellen nincs védelem, de ez nem így van! Igaz, hogy csak egy, de egy módszer van, ami akkor is működik, ha nem is tudjuk, hogy mi(k) a confounder(ek).

Ez a módszer pedig nem más, mint az, ha az alanyokat véletlenszerűen -- például pénzfeldobással -- sorsoljuk a kezelt és kontrollcsoportok egyikébe! Ezt szokás **randomizációnak** hívni. Ebben az esetben ugyanis a fiatalok és idősek aránya között nem lesz semmilyen szisztematikus^[Érdemes picit pontosítani, hogy mit értünk „szisztematikus” alatt, hiszen valaki azt mondhatná (joggal), hogy éppenséggel a pénzfeldobásnál is előfordulhat, hogy az összes fiatal az egyik csoportba kerül, míg az összes idős a másikba. A dolog úgy nyer értelmet, ha hosszú távon szemléljük a kérdést, mintha képzeletben újra meg újra megismételnénk a randomizálást. Lehet, hogy előfordulhat az előbbi helyzet is, de az ellenkezője is, és *átlagosan* kiegyensúlyozott lesz a két csoport. Belátható, hogy a klinikai vizsgálat szempontjából ez fog számítani, ugyanis a kiértékelésnél megadjuk az eredmények bizonytalanságát is -- ezt nemsokára látni is fogjuk -- és ez épp úgy van számolva, hogy figyelembe veszi ezt az ingadozást [@senn2013].] eltérés a két csoport között. De ennél jóval fontosabb, hogy *semmi másban sem* lesz szisztematikus eltérés! Azaz: abban sem, amiről eszünkbe sem jut, hogy confounder! Ha véletlenül a zöld szeműek inkább kapnak gyógyszert, és a zöld szemszín valamiért javítja a túlélést, az bizonyosan elrontana minden vizsgálatot, mert nincs olyan gyógyszervizsgálat a világon, ahol a szemszínt egyáltalán felírnák -- de vegyük észre, hogy a randomizálás *még ekkor is* működni fog! Hiszen ha pénzfeldobással sorsoltuk az alanyokat két csoportba, akkor szemszínben *sem* lesz szisztematikus eltérés a csoportok között, azaz nem baj, hogy hat a túlélésre. Úgy is fogalmazhatunk, hogy a randomizáció -- ha jól végzik -- automatikusan és teljesen megoldja a confounding problémáját, mert az összes potenciális confoundert kiszűri, azokat is, amikről nincs információnk, sőt, azokat is, amikről eszünkbe sem jut, hogy confounderek.

Ha ez ilyen egyszerű, és ezzel teljeskörűen megoldhatjuk a problémát, akkor adódik a kérdés, hogy miért nem csinálunk mindig randomizált, kontrollált vizsgálatot? Egyrészt, bizonyos helyzetekben ezt fizikailag vagy etikailag lehetetlen elvégezni. Ha érdekel minket, hogy a vöröshús-fogyasztás rákot okoz-e, nem lehet embereket randomizáltan etetni vörös hússal, ha érdekel, hogy a császármetszéssel születés tényleg cukorbetegséget okoz-e, nem lehet szülő nőket randomizáltan császármetszésre küldeni (függetlenül attól, hogy szükségük van-e rá...) stb. A példák is mutatják, hogy ez inkább a betegségek okait, terjedését kutató tudományágban, az epidemiológiában tipikus helyzet. Mi a probléma gyökere? Az, hogy a randomizáció elvégzéséhez szükséges, hogy a vizsgált tényezőt mi határozzuk meg, mi „adagoljuk” az alanyoknak. A probléma tehát az, hogy erre sokszor nincs lehetőség.

Azokat a kutatásokat, ahol a vizsgált tényezőt nem a kutatók irányítják, csak passzíve feljegyzik, hogy az alanyokkal mi történt vagy történik, anélkül, hogy bármivel is befolyásolnák az eseményeket, **megfigyeléses vizsgálatnak** nevezzük. Ha a kutatók aktívan befolyásolják a vizsgált tényezőt, **kísérletes vizsgálatról** beszélünk.

Míg az epidemiológiában legtöbbször csak megfigyeléses vizsgálatot lehet végezni, addig a gyógyszerkutatásban nagyon sokszor van mód kísérlet végzésére -- randomizált, kontrollált kísérletre -- is.

A kísérletek hatalmas előnye tehát, hogy elvileg mentesek tudnak lenni a confoundingtól, anélkül, hogy ehhez bármit kellene tennünk a randomizáláson túl. (Ez nem jelenti azt, hogy egy klinikai kísérletben, ha van információnk egy kimenetet befolyásoló változóról, akkor azt más okokból ne lenne célszerű felhasználni, de ez már technikai kérdés.) Megfigyeléses vizsgálatnál, bármilyen ügyesen is járunk el, mindig a fejünk felett fog lebegni, hogy mi van, ha valamilyen confounderről megfeledkeztünk. A kísérletek egy további előnye, hogy lehet maszkolni a kezelés tényét, de erről majd kicsit később.

Hozzá kell tenni, hogy a klinikai kísérleteknek hátrányaik is vannak a megfigyeléses vizsgálatokkal szemben (azon túl persze, hogy nem mindig végezhetőek el). Az egyik, hogy a kísérletekbe bevont alanyok száma jellemzően jóval kisebb, az utánkövetésük hossza pedig általában csak jóval rövidebb tud lenni, mint egy megfigyeléses vizsgálatnál. Ez az oka annak, hogy az utóbbi időben egyre többször végeznek megfigyeléses vizsgálatot a gyógyszerkutatásban is.

::: {.invisible style="display:none"}
@greenland1986
@maldonado2002
@maldonado2013
@maldonado2016
@dawid2000
@senn2013
:::