# A kontrollálás kérdései

## A kontrollcsoport megválasztása, aktív kontroll

Az eddigi leírásban végig "kezelt" és "kontroll" csoportokat emlegettük, hallgatólagosan feltéve, hogy a kezelt csoport a vizsgált gyógyszert kapja, a kontrollcsoport pedig semmit. Ez csakugyan egy lehetséges elrendezés (noha ebben az esetben sem szerencsés, ha szó szerint semmit nem kap a kontrollcsoport -- de erre a kérdésre a következő pontban részletesen kitérünk), ám van, hogy etikai okokból nem követhető ez az irány: ha a betegségre van ismerten hatásos és biztonságos gyógyszer, és annak megvonása lényeges és biztos kockázatot jelent, akkor nem engedhető meg, hogy a betegek egy része ne kapjon kezelést.

Abban az esetben, ha erre tekintettel nem a semmihez, hanem egy *másik* gyógyszerhez hasonlítják a vizsgált készítményt, **aktív kontrollról** szokás beszélni. Ez a fent vázolt etikai problémákat megoldja ugyan, de egy sor módszertani problémát teremt, kezdve azzal, hogy így valójában nem azt tudjuk meg, hogy a gyógyszer hat-e, hanem azt, hogy *legalább ugyanannyira* hat, mint a másik. Sok esetben ráadásul az nem is cél, hogy a gyógyszer jobb legyen, mint a másik, ezért igazából csak annyit tudunk és akarunk bizonyítani, hogy *ugyanannyira* hat, de ehhez meg statisztikai okokból kifolyólag általában lényegesen nagyobb mintanagyság is kell. További probléma, hogy azt, hogy a *másik* hat-e, nem tudjuk meg magából a vizsgálatból, külső feltevéseket kell elfogadnunk -- különben akár még az is előfordulhat, hogy azért hat egyformán mindkét gyógyszer, mert valójában mindkettő hatástalan. Végezetül az is bonyolítja a helyzetet aktív kontroll esetén, hogy míg semmit csak egyféleképp lehet adni, addig valamit elég sokféleképp -- azaz ilyenkor számítani fog az is, hogy konkrétan milyen gyógyszerhez viszonyítunk, akár még az is, hogy milyen adagolásban adva. Tehát ebben az esetben az eredmény egy újabb tényezőtől fog függeni, amit meg lehet -- jó- vagy kevésbé jóhiszeműen -- szerencsétlenül, vagy félrevezető módon is választani.

A fentiek miatt az aktív kontrollálás melleti döntés sokszor finom mérlegelést igényel. Megengedhető a nem aktív kontroll, ha a betegség amúgy sem feltétlenül igényel orvosi ellátást (férfias típusú kopaszodás), ha minimális kellemetlenséggel jár a kezeletlenül hagyás is (enyhe köhögés, átmeneti szédülés), de ha módszertanilag nyomós indoka van, akár nagyobb kockázat is elfogadható. Annak természetesen nem tehető ki egy beteg, hogy meghaljon, de ha a készítmény nem, vagy nem igazoltan csökkenti a halálozást, csak mondjuk a kórházban töltött időt rövidíti néhány nappal, akkor ez egy olyan kockázat, aminél teljes írásos felvilágosítás után egy felnőtt emberre rábízható, hogy eldöntse, vállalja-e annak érdekében, hogy az emberiség orvosi tudása bővüljön. (Természetesen megfelelő korai leállítási szabályokkal arra az esetre, ha kiderülne, hogy a gyógyszer mégis csökkenti a halálozást is; erről később még szó lesz.)

Nagyon fontos ennek kapcsán hangsúlyozni, hogy a nem aktív kontroll sem azt jelenti, hogy a kontrollcsoport nem kap kezelést. A szokásos ellátást természetesen *ugyanúgy* megkapja mindkét csoport, pont emiatt ez nem okoz sem etikai, sem statisztikai problémát, mert a csoportok közti különbség továbbra is csak abban van, hogy ezen a szokásos ellátáson *felül* mit kapnak, vizsgált készítményt vagy semmit. Így, amennyiben randomizáltak, az eredmény továbbra is csak a kísérleti szernek -- és a véletlen ingadozásnak -- tulajdonítható.

## Placebóhatás, kezeletlen és placebo kontroll, a kezelés maszkolása

Régóta ismert, hogy a kezelésben részesülés *tudata* önmagában képes hatást kiváltani, pozitív hatást, ha a kezelésben részesüléshez pozitív várakozások kapcsolódnak -- ezt szokás **placebóhatásnak** nevezni [@price2008]. (Az máig vita tárgya, hogy ez mennyire érvényesül a szubjektívebb, tehát a beteg saját értékelésén alapuló, és mennyire az objektív, például műszerrel lemért végpontokon.) Ez azért fontos, mert ha úgy döntünk, hogy a kezelést a kezelés hiányához hasonlítjuk, akkor nem célszerű azt tenni, hogy a kontrollcsoportnak nem adunk semmit, hiszen ekkor azonnal megtudnák, hogy ők a kontrollcsoportba tartoznak, és hasonlóan a kezelt csoport is azonnal tudná, hogy ők a kezelt csoportba tartoznak, így a legtökéletesebb randomizálás mellett is létrejönne egy eltérés a két csoportban. Igaz, hogy "csak" a kezelésben részesülés tudatában, de a placebóhatás pont azt jelenti, hogy már ez is probléma lehet. Ehhez persze az is kell, hogy megállapodjunk abban, hogy a placebóhatást nem tekintjük a gyógyszernek betudható hatásnak (mivel az nem is a gyógyszer *specifikus* hatása, hanem magáé a gyógyszerszedésé, függetlenül attól, hogy mit szed az alany). Ezt az összehasonlítási alapot szokás **kezeletlen kontrollnak** nevezni.

A placebo hatás egyfajta "kivonását" jelenti, ha -- amennyiben megoldható -- a kontrollcsoportnak egy, a vizsgált gyógyszerrel mindenben azonos, tőle megkülönböztethetetlen szert kell kapnia, amely egyetlen dologban tér el a vizsgált készítménytől: abban, hogy nincs benne hatóanyag. Ezt szokás **placebónak** nevezni, és az így kontrollált vizsgálatot pedig **placebókontrollált kutatásnak** hívjuk.

Sokan azt gondolják, hogy a placebo adása pusztán a kontrollcsoport "ügye", de ez tévedés: a placebo adása *ugyanannyira* érdekes a kezelt csoport számára is, hiszen innentől *ők sem* tudhatják, hogy melyik csoportban vannak! Azaz megvalósul a kiindulási cél, hogy ti. ne legyen ebben (sem) eltérés a két csoport között.

Azt a helyzetet, ha a betegek nem tudják, hogy kezelt vagy kontrollcsoportba tartoznak, amely tehát csak placebókontrollal vagy aktív kontrollal érhető el, szokás **maszkolásnak** nevezni. Ha csak a beteg nem ismeri a csoportját, de a kezelőorvos igen, akkor **egyszeres maszkolásról** (**egyszeres vak próbáról**) szokás beszélni. Érdekes módon még ez sem tökéletes: ha az orvos tudja a besorolást, az is baj lehet (akár teljesen szándékolatlanul, de sugallhatja a betegnek, viselkedésével, testbeszédével, hogy melyik csoportba tartozik), ezért a magasabb bizonyítóerő érdekében még jobb, ha az *orvos sem* tudja, hogy a beteg melyik csoportba tartozik. Ilyenkor beszélünk **kétszeres maszkolásról** (**kettős vak próbáról**). A nem maszkolt vizsgálatokat **nyílt elrendezésű** vizsgálatnak is szokták nevezni.

Aktív kontroll esetén kisebb problémát jelent a nyílt elrendezés, hiszen ahhoz vélhetően kisebb várakozások fűződnek, hogy két, kimondhatatlan nevű szer közül pontosan melyiket kapja a beteg, annál mindenesetre bizonyosabb kisebb, mint a kap/nem kap helyzetben. (De a "kisebb" sem feltétlenül nulla, jól ismert például, hogy az újabb, jobban reklámozott, drágább szerek jobb placebót jelentenek.)

Vannak esetek, amikor a kontrollálás technikai okokból nehezebben kivitelezhető, például ha nem egy gyógyszerről, hanem egy műtétről van szó, amit placebóval szeretnénk kontrollálni, vagy, ha aktív kontrollt választunk egy gyógyszernél, de a vizsgált és a kontroll gyógyszer formája eltérő, például az egyik inhaláló szer, a másik filmtabletta. Sokszor azonban még ezek a problémák is feloldhatóak, például megfelelő etikai feltételek teljesülése esetén "álműtét" is végezhető [@wartolowskag2014], amikor a beteg ugyanolyan műtét előtti és utáni ellátáson keresztül megy keresztül, mint egy igazi műtétnél, sőt, akár még a műtéti bemetszést és összevarrást is megkapja, csak épp a kettő között nem csinálnak semmit. Ha pedig a két gyógyszerforma eltérő, akkor megtehetjük, hogy mindenki inhaláló szert és filmtablettát *is* kap, de az egyik csoportban a betegek placebót inhalálnak és a tablettában lesz az aktív szer, a másikban fordítva (double dummy elrendezés).

## Párhuzamos és keresztezett kontroll

Az eddigi leírásból úgy tűnhet, hogy a klinikai kísérlet úgy néz ki, hogy begyűjtjük a betegeket, véletlenszerűen két csoportba soroljuk őket, alkalmazzuk a gyógyszert, majd utánkövetjük az alanyokat és lemérjük a végpontot. A legtöbb esetben tényleg ez történik, azzal az apró kiegészítéssel, hogy valójában a randomizálás -- és az azt követő kezelés -- nem egyetlen időpontban történik az összes betegre, hanem folyamatosan, ahogy a betegek érkeznek a vizsgálatba; még az sem ritka, hogy valamelyik beteg teljesen befejezi az egész vizsgálatot, amikor más még csak épp randomizálásra kerül [@senn2013]. Ezzel együtt is, az ilyen kutatásokat **párhuzamosan kontrollált** vizsgálatnak szokás nevezni, utalva arra, hogy az előbbi technikai kérdéstől eltekintve valóban párhuzamosan fut a kezelt és kontroll csoport kezelése.

Bizonyos esetekben azonban van egy alternatív lehetőség: az, hogy *ugyanazok* a betegek alkotják a kezelt és kontrollcsoportot, akik így nem egymással párhuzamosan, hanem egymás *után* kerülnek kezelésre. Magyarán: a bevont alanyokat véletlenszerűen kettéosztjuk, egyik részük előbb kezelést kap, utána placebót vagy a másik gyógyszert, a másik része pedig pont fordítva. Az ember első ránézésre azt is gondolhatja, hogy ezzel igazából megoldottuk a felvezetőben említett problémáját az időgép hiányának, hiszen így mégis *ugyanazon* emberen mértük le a kezelés és a kezeletlenség hatását is. Valójában ez sem teljesen igaz, hiszen elképzelhető, hogy nem mindegy, hogy melyik időszakban kapja az alany a kezelést (ha valamiért a kezelés hatása változik időben), az sem feltétlenül mindegy, hogy úgy kapja a kontrollt, hogy előtte kapott kezelést (lehet, hogy a kezelésnek van időben elnyúló hatása), de a legnagyobb probléma, hogy ez a fajta elrendezés sokszor fizikailag megvalósíthatatlan: nem lehet ilyet csinálni akkor, ha a beteg teljesen meggyógyul a kezeléstől, hiszen utána már hiába adunk neki mást. Akkor sem valósítható meg ez az elrendezés, ha a beteg állapota súlyosbodik az első kezelés alatt vagy után (szélsőséges esetben ha meghal, hiszen akkor megint csak hiába akarnánk később mást adni). Valójában tehát krónikus, stabil betegségeknél van mód rá, ahol a kezelés "csak" az állapoton javít, és ez az esetleges javulás nem túl hosszú kezelés után előáll.

Ha meg lehet valósítani ezt az elrendezést, amit **keresztezett vizsgálatnak** szokás nevezni, akkor az viszont sok előnnyel bír, abból fakadóan, hogy minden alany lényegében a saját maga kontrollja, így egy sor egyénre jellemző tulajdonság (életkor, nem, milliónyi genetikai tényező) *automatikusan* ki van egyensúlyozva. Az ilyen vizsgálatok ezért általában hatásosabbak, azaz kisebb a véletlen ingadozás bennük (ugyanazzal a mintanagysággal pontosabb becslés lehetséges, avagy ugyanolyan pontossághoz kisebb mintanagyság is elég), és lehetővé teszik a betegek közti -- nem csak a kezelések közti -- ingadozás becslését is [@senn2003].
