# A végpontok megválasztásának és mérésének kérdései
\chaptermark{A végpontok megválasztása és mérése}

## A végpont fogalma, elsődleges és másodlagos végpontok

A **végpont (hatásmutató)** a vizsgálat klinikailag érdekes kimenetének lemérése, annak számszerűsítése, hogy mi történt a beteggel akár a gyógyszer hatásosságát, akár a biztonságát tekintve. Végpont lehet, hogy a beteg meghalt-e, hogy mennyi lett a vérnyomása, hogy mennyi idő után épült fel, felszívódott-e egyáltalán a gyógyszer, vagy az, hogy egy bizonyos mellékhatás fellépett-e nála. Az külön kérdéskör, hogy ezekből az eredményekből hogyan lehet egyetlen számba sűrítve kifejezni a gyógyszer hatását, de ezzel most nem foglalkozunk.

Látható, hogy végpontból több is lehet, de ezeket általában rangsorolni szokták: elsődleges végpontnak nevezzük azt, ami a legfontosabb kimenet a vizsgálat kérdése szempontjából, és ami alapján a kísérletbe bevont betegek számát tervezik. Hiszen láttuk, hogy egy bizonyos méretű hatás -- adott erővel és adott szignifikanciaszinten történő -- kimutatásához szükséges beteglétszám előre meghatározható statisztikai módszerekkel. Na de melyik hatásról beszélünk? Arról, hogy a gyógyszer hogyan változtatja a halálozások számát? Arról, hogy hogyan változtatja az infarktus előfordulását? Ezek nagyon különböző beteglétszámokat tehetnek szükségessé, hiszen halálozásból tipikusan kevesebb van mint infarktusból, így annak csökkentése kisebb méretű hatás, ezért a kimutatásához több betegre lesz szükség. A vizsgálatban mindig ki kell választani az^[Előfordulhat, hogy egynél több elsődleges végpont van, ebben az esetben azonban a többszörös összehasonlítások pontban leírt kérdésekre oda kell figyelni a vizsgálat tervezése és kiértékelése során.] elsődleges végpontot, arra meghatározni a kimutatni tervezett hatást, és ez alapján tervezni mintanagyságot. Az összes többi, ún. másodlagos végpontra nincs méretezve a kutatás ereje.

## Kemény és helyettesítő végpontok

Az előbbi gondolatnak tulajdonképpen még messzebbre vezető következményei is vannak. Gondoljunk bele a következőbe: miért adunk a betegeknek vérnyomáscsökkentő gyógyszert? Azért, hogy ritkábban kapjanak infarktust, stroke-ot, vagy még általánosabban fogalmazva: hogy tovább legyen jó az egészséggel összefüggő életminőségük, tovább legyenek munkaképesek, később haljanak meg. Ezért ha egy új vérnyomáscsökkentő gyógyszerjelöltet vizsgálunk, akkor *elvileg* ezeket kell végpontnak megtenni: infarktus előfordulása, stroke előfordulása, halálozás. Az ilyen, beteg számára igazán releváns végpontot szokták **kemény végpontnak** nevezni, és ha mód van rá, ilyet célszerű mérni. Igen ám, de a vérnyomáscsökkentős példánkban belefutunk egy problémába: ha csak nem nagyon rossz állapotú alanyokról van szó, akkor ezek az események elég ritkák lesznek, illetve sokat kell várni a kialakulásukra. Ami persze általában jó hír, de most, kutatástervezési szempontból nem az: a ritkaság statisztikai szempontból azt jelenti, hogy rengeteg alanyra, a lassan kialakuló jelleg pedig azt, hogy nagyon hosszú utánkövetési időre lesz szükség, és ezek egy ponton túl kivitelezhetetlenek.

Mit csináljunk tehát a vérnyomáscsökkentő esetében? Azt fogjuk lemérni, hogy a vérnyomást csökkenti-e! Hiszen ez mindenkinél lemérhető, és rövid időn belül lemérhető (ráadásul könnyen, veszélytelenül és olcsón). De bármennyire is kézenfekvőnek tűnik ez, vegyük észre, hogy itt van egy háttérfeltételezés: az, hogy a vérnyomás csökkentése *tényleg* maga után vonja a kemény végpontok, például az infarktus vagy a halálozás csökkenését is! Ezt muszáj biztosan tudnunk, különben az egész vizsgálattal nem megyünk semmire. Az ilyen végpontokat szokás **helyettesítő végpontnak** nevezni. A helyettesítő végpontok sok esetben hasznosak, sőt, néha ezek teszik egyáltalán lehetővé kutatások elvégzését, de másrészről a használatuk "veszélyes üzem", mert az előbbi feltétel teljesülését alaposan meg kell vizsgálni. Ezzel kapcsolatban itt csak arra hívjuk fel a figyelmet, hogy *önmagában* az, hogy valami együttmozog a végponttal (a magasabb vérnyomású betegek körében gyakoribb az infarktus) még *nem* bizonyítja, hogy jó helyettesítő végpont! Az, hogy a helyettesítő végpont javítása maga után vonja a kemény végpont javulását is, egy sokkal erősebb feltétel mint az, hogy a kettő együtt jár; ha erről megfeledkeznénk, akkor egy fogfehérítő szerről kimutathatnánk, hogy hatásos a tüdőrák ellen (gondoljuk végig!).

## Több végpont használata, többszörös összehasonlítások helyzete
\chaptermark{Többszörös összehasonlítások}

A statisztikai szignifikanciánál láttuk, hogy a szokásos 5%-os szignifikanciaszint használata azt jelenti, hogy ha nincsen hatás, mi 5% valószínűséggel fogunk mégis, a véletlen ingadozás miatti pech miatt, tévesen hatást kimutatni. (És láttuk, hogy ezt a szintet csökkenteni sem feltétlenül érdemes, hiszen akkor meg a valódi hatások detektálását is megnehezítjük.) Ez teljesen rendben is van akkor, ha *egyféle* hatást vizsgálunk meg. De mi történik akkor, ha például kétféle végpontot vizsgálunk, mondjuk azt is megnézzük, hogy a gyógyszer az infarktus előfordulását csökkenti-e, és azt is, hogy a stroke előfordulását csökkenti-e?

Külön-külön vizsgálódva nincsen semmi különös: ha a gyógyszer egyikre sem hat, akkor 5% valószínűséggel fogunk mégis hatást kimutatni mindkettő esetében. Ha azonban azt kérdezzük, hogy mekkora valószínűséggel fogunk *legalább az egyiknél* tévesen hatást kimutatni, az máris rögtön nagyobb lesz, mint 5%! Gondoljunk bele, a dolog úgy is felfogható, hogy van egy cinkelt pénzérménk, ami 5% valószínűséggel mutat fejet feldobásnál, akkor annak a valószínűsége 5%, hogy egy dobásból fejet kapunk, de annak a valószínűsége, hogy két dobásból legalább egy fejet kapunk, nyilván jóval nagyobb. Az meg pláne, hogy 10-ből dobunk legalább egy fejet. Ha tehát "vagylagosan" vizsgálódunk, azaz akkor mondjuk, hogy találtunk valamit, ha *bármelyik* végpontot találunk hatást, akkor óvatosan kell eljárni.

Ez egy példa a **többszörös összehasonlítások helyzetének** nevezett általános jelenségre, ami akkor lép fel, ha a fenti értelemben "vagylagosan" végzünk több vizsgálatot [@schulz2005a]. A több végponton kívül számos eset van, ami valójában ugyanerre vezet, például ha több időpontban is megvizsgáljuk a gyógyszer hatását, vagy ha több betegcsoportban is megvizsgáljuk a gyógyszer hatását (ezekre később még külön is kitérünk), de az alapprobléma mindenhol ugyanaz: ha több összehasonlítást végzünk, megnő annak a valószínűsége, hogy tévesen hatást mutatunk ki. Ilyenkor szükség lehet arra, hogy megfelelő statisztikai korrekciókat tegyünk. Ezeknek számos módszerük van, pusztán csak az érzékeltetés kedvéért, az egyik ilyen lehetőség, hogy az egyes vizsgálatok szignifikanciaszintjét csökkentjük. Hiszen a jelenség az volt, hogy a "fals találat" valószínűsége megnő ahhoz képest, mint az egyes tesztek szignifikanciaszintje, akkor csökkentsük le ez utóbbit, hogy még a megnövekedés után is annyi legyen, ami számunkra elfogadható, például 5%!
